### ISSUE TITLE
Cannot Show Your Location

### ISSUE THREAD

**Issue by HarryWindsor** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#156]
When I try to find my location on maps I always get an error: `This Mac cannot determine your current location because it does not have Wi-Fi.`.

I am able to find my WiFi network and connect to it, so this part works fine. Just the location services do not work.

```yaml
802.11n WLAN Adapter:
  Product ID: 0x8176
  Vendor ID: 0x0bda  (Realtek Semiconductor Corp.)
  Version: 2.00
  Serial Number: 00e04c000001
  Speed: Up to 480 Mb/s
  Manufacturer: Realtek
  Location ID: 0x14200000 / 1
  Current Available (mA): 500
  Current Required (mA): 500
  Extra Operating Current (mA): 0
```

Is there something I missed?

![Screen Shot 2021-11-30 at 19 58 53 PM](https://user-images.githubusercontent.com/40882642/144110753-4bb11300-6016-412f-b15f-90caea68d449.png)
